Homework 2
KirillVitko/2019-2-Atom-Frontend-K-Vitko pull request #2
Opened 2019-10-15 12:06 UTC by KirillVitko

2019-10-15 12:38 UTC, priver requested changes
Нет описания PR

2019-10-15 12:40 UTC, KirillVitko commented
Новый PR сделать с описанием? Или можно просто комментарий добавить с описанием?

2019-10-15 12:42 UTC, priver reviewed
![image](https://user-images.githubusercontent.com/1700074/66832336-62818680-ef62-11e9-8a5b-be13e852e21f.png)

2019-10-15 12:42 UTC, priver commented on web-components/src/components/MessageValue.js
> +                const newname = document.createElement('div')
нужен отдельный компонент для сообщения

2019-10-15 12:53 UTC, KirillVitko commented on web-components/src/components/MessageValue.js
> +                const newname = document.createElement('div')
Я добавлял к тексту дату и имя. Нужно создать отдельно сообщение и в него добавлять текст сообщения, дату и отправителя?

2019-10-21 10:31 UTC, priver requested changes

2019-10-21 10:31 UTC, priver commented on web-components/src/components/MessageValue.js
> +                const newname = document.createElement('div')
Нужно создать шаблон и класс для сообщения, зарегистрировать его в customElements, а дату и текст передавать с помощью атрибутов (`createElement('my-message')`, `message.setAttribute('date', date)`)

2019-11-02 20:40 UTC, closed without merging