Devel
KirillVitko/2019-2-Atom-Frontend-K-Vitko pull request #4
Opened 2019-11-18 14:07 UTC by KirillVitko

Сделал ДЗ3+ДЗ4
Добавил список диалогов и способы перехода между окнами
Добавил различные стили/анимации

2019-11-19 04:03 UTC, martinkomitsky requested changes
У тебя появился вертикальный скролл в шапке. И наложение картинки на текст. Нехорошо
![image](https://user-images.githubusercontent.com/14847018/69115721-a48a7480-0a9a-11ea-948c-8dba2d2a22c0.png)

2019-11-19 14:36 UTC, KirillVitko commented
> У тебя появился вертикальный скролл в шапке. И наложение картинки на текст. Нехорошо
> ![image](https://user-images.githubusercontent.com/14847018/69115721-a48a7480-0a9a-11ea-948c-8dba2d2a22c0.png)

Это при зуме или на разрешении, отличающимся от моего?

2019-11-20 04:14 UTC, martinkomitsky commented
> Это при зуме или на разрешении, отличающимся от моего?

это я просто открыл страницу

2019-11-24 12:59 UTC, martinkomitsky commented
@KirillVitko будем исправлять?

2019-11-24 14:45 UTC, KirillVitko commented
Поправил
Поменял проценты на пикселе везде, где работал с высотой

2019-11-24 15:46 UTC, martinkomitsky approved these changes
ok, 6 & 6

2019-11-24 15:46 UTC, merged